WORKDIR /app

# Copiar e instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código del proyecto
COPY . .

# Comando de inicio
# Usamos el formato Shell (sin [] ni sh -c) para que $PORT se expanda correctamente.
# Una única línea CMD sin la variable $PORT escrita a mano
CMD ["gunicorn", "--chdir", "api", "app:app"]
